# Generated by Django 3.1.2 on 2020-11-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_complete_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='small_image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
