# Generated by Django 3.1.2 on 2020-11-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_phonecheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecheck',
            name='check_number',
            field=models.CharField(max_length=50),
        ),
    ]
