# Generated by Django 3.1.2 on 2020-11-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201106_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertosubscribe',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
