# Generated by Django 3.1.2 on 2020-11-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201110_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shelf_name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
