# Generated by Django 3.1.2 on 2020-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_shelf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shelf_name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
